# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
COPY ./app /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run endpoint.py when the container launches
# CMD ["uvicorn", "endpoint:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["streamlit", "run", "--server.port", "8501", "app.py"]
CMD ["/bin/sh", "/app/start.sh"]